spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
